language: node_js
os:
  - linux
  - osx

node_js:
  - "10"
  - "10.15"
  - "10.19"
  - "12"
  - "14"

install:
  - npm version
  - npm install

jobs:
  include:
    - script: npm test
    - stage: release
      node_js: lts/*
      script: skip
      before_deploy: "echo 'Releasing to npm'"
      deploy:
        on:
          branch: master
          condition:  $TRAVIS_OS_NAME == linux
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
