language: node_js
os:
  - linux

node_js:
  - "10.19"
  - "12"
  - "14"
  
install:
  - npm version
  - npm install

jobs:
  include:
    - stage: Test
      script: npm test
      if: NOT branch = master
    - stage: release
      if: branch = master
      node_js: "12"
      script: skip
      before_deploy: "echo 'Releasing to npm'"
      deploy:
        on:
          branch: master
          condition:  $TRAVIS_OS_NAME == linux
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
